services:
  app1:
    container_name: app1
    build: 
      context: ./zkWorker
      dockerfile: Dockerfile
    environment:
      ZOOKEEPER_HOST_NAMES: zoo1:2181,zoo2:2181,zoo3:2181

  zoo1:
    container_name: zoo1
    hostname: zoo1
    image: zookeeper:3.8
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    container_name: zoo2
    hostname: zoo2
    image: zookeeper:3.8
    restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    container_name: zoo3
    hostname: zoo3
    image: zookeeper:3.8
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
